spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/questiondb
    username: postgres
    password: r@98mrmr
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always